# Generated by Django 5.2.1 on 2025-05-23 01:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ocupado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Posto de Atendimento',
                'verbose_name_plural': 'Postos de Atendimento',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_andamento', models.BooleanField(default=False)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('contador_senha_normal', models.IntegerField(default=0)),
                ('contador_senha_prioritaria', models.IntegerField(default=0)),
                ('senhas_atendidas', models.IntegerField(default=0)),
                ('desistencias', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Simulação',
                'verbose_name_plural': 'Simulações',
            },
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('P', 'Prioritária')], default='N', max_length=1)),
                ('data_hora_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendida', models.BooleanField(default=False)),
                ('desistiu', models.BooleanField(default=False)),
                ('data_hora_atendimento', models.DateTimeField(blank=True, null=True)),
                ('posto_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senhas_atendidas', to='atendimento.postoatendimento')),
            ],
            options={
                'verbose_name': 'Senha',
                'verbose_name_plural': 'Senhas',
                'ordering': ['data_hora_emissao'],
            },
        ),
        migrations.AddField(
            model_name='postoatendimento',
            name='senha_atual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posto_atual', to='atendimento.senha'),
        ),
    ]
